### ISSUE TITLE
Error "Module did not self-register" on "npm start"

### ISSUE THREAD

**Issue by gnapse** [AbeEstrada/react-boilerplate#2]
Hi, I'm getting the following error when trying to start the app:

```
$ npm start

> reactjs-boilerplate@0.1.0 start /Users/ernesto/code/reactjs/boilerplate
> gulp serve

module.js:501
  var paths = [path.resolve(process.execPath, '..', '..', 'lib', 'node')];
                       ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/ernesto/code/reactjs/boilerplate/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:211:15)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
```

**Comment by AbeEstrada** [comment]
This boilerplate uses `gulp-sass` to compile the `.scss` files, and `gulp-sass` relies on `node-sass` that is the library that is failing in v0.12.0, `gulp-sass` has the fix coming soon https://github.com/dlmanning/gulp-sass/pull/193

**Comment by AbeEstrada** [comment]
You can run `npm update` or `npm install` again and it will install `node-sass@2.0.1`, `npm start` works now.

**Comment by gnapse** [comment]
That did the trick. Thanks!
